### ISSUE TITLE
Cannot access a disposed object on Android 

### ISSUE THREAD

**Issue by amirvenus** [shinyorg/xunit-maui#2]
Hi,

I have a .net6-android project and I have installed this solution so that I can write platform-specific tests. 

There is only one issue though and that is the unexpected disposal of the MainApplication. 

Is there a way to ensure I can access the Application's context (i.e. using Platform.AppContext) without it being disposed?

I am currently getting this exception:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'OnBoardPlatformTests.MainApplication'.
   at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:line 152
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 384
   at Android.Content.ContextWrapper.get_Resources() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Content.ContextWrapper.cs:line 638
   at Microsoft.Maui.ApplicationModel.AppInfoImplementation.get_RequestedLayoutDirection() in D:\a\_work\1\s\src\Essentials\src\AppInfo\AppInfo.android.cs:line 97
   at Microsoft.Maui.MauiContextExtensions.GetFlowDirection(IMauiContext mauiContext) in D:\a\_work\1\s\src\Core\src\MauiContextExtensions.cs:line 83
   at Microsoft.Maui.IViewExtensions.GetEffectiveFlowDirection(IView view) in D:\a\_work\1\s\src\Core\src\Core\Extensions\IViewExtensions.cs:line 19
   at Microsoft.Maui.IViewExtensions.GetEffectiveFlowDirection(IView view) in D:\a\_work\1\s\src\Core\src\Core\Extensions\IViewExtensions.cs:line 15
   at Microsoft.Maui.IViewExtensions.GetEffectiveFlowDirection(IView view) in D:\a\_work\1\s\src\Core\src\Core\Extensions\IViewExtensions.cs:line 15
   at Microsoft.Maui.Layouts.LayoutExtensions.ShouldArrangeLeftToRight(IView view) in D:\a\_work\1\s\src\Core\src\Layouts\LayoutExtensions.cs:line 212
   at Microsoft.Maui.Layouts.LayoutExtensions.AlignHorizontal(IView view, Rect bounds, Thickness margin) in D:\a\_work\1\s\src\Core\src\Layouts\LayoutExtensions.cs:line 83
   at Microsoft.Maui.Layouts.LayoutExtensions.ComputeFrame(IView view, Rect bounds) in D:\a\_work\1\s\src\Core\src\Layouts\LayoutExtensions.cs:line 63
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 116
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 109
   at Microsoft.Maui.Layouts.LayoutExtensions.ArrangeContent(IContentView contentView, Rect bounds) in D:\a\_work\1\s\src\Core\src\Layouts\LayoutExtensions.cs:line 192
   at Microsoft.Maui.Controls.ContentPage.Microsoft.Maui.IContentView.CrossPlatformArrange(Rect bounds) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\ContentPage.Impl.cs:line 35
   at Microsoft.Maui.Platform.ContentViewGroup.OnLayout(Boolean changed, Int32 left, Int32 top, Int32 right, Int32 bottom) in D:\a\_work\1\s\src\Core\src\Platform\Android\ContentViewGroup.cs:line 89
   at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Views.ViewGroup.cs:line 3616
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 418

**Comment by aritchie** [comment]
No response from user.
